#!/usr/bin/env python3
"""
parse_tasks.py — deterministic tasks resolver for the Atlas dashboard.

Source of truth = Tasks/TASKS.md (the human checklist). An item is OPEN iff its
line is an unchecked box `- [ ]`. Title + status come from that line; the section
heading gives the project, enriched/overridden by the ledger's Area column.

Writes Dashboard/data/tasks.md (frontmatter + static body). No LLM needed.

Usage: python3 Skills/dashboard-refresh/scripts/parse_tasks.py
       (run from anywhere; vault root is derived from this file's location)
"""
import re
import sys
from pathlib import Path
from datetime import datetime

VAULT = Path(__file__).resolve().parents[3]   # …/Atlas
TASKS = VAULT / "Tasks" / "TASKS.md"
LEDGER = VAULT / "Tasks" / "ledger.md"
OUT = VAULT / "Dashboard" / "data" / "tasks.md"

OPEN_RE = re.compile(r"^- \[ \] \*\*(T\d+)\s*[—-]\s*(.+?)\*\*\s*_\(([^,]+),\s*(P\d)\)_")
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$")


def ledger_areas():
    areas = {}
    if not LEDGER.exists():
        return areas
    for line in LEDGER.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| T"):
            continue
        cols = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cols) >= 3 and re.match(r"^T\d+$", cols[0]):
            areas[cols[0]] = cols[2]  # Area column
    return areas


def parse_open():
    areas = ledger_areas()
    items, section = [], "—"
    for line in TASKS.read_text(encoding="utf-8").splitlines():
        m = SECTION_RE.match(line)
        if m:
            section = m.group(1).strip()
            continue
        m = OPEN_RE.match(line)
        if m:
            tid, title, status, _prio = m.groups()
            items.append({
                "id": tid,
                "title": title.strip(),
                "status": status.strip().lower(),
                "project": areas.get(tid, section),
            })
    return items


def yaml_escape(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    if not TASKS.exists():
        sys.exit(f"TASKS.md not found at {TASKS}")
    items = parse_open()
    by_status = {}
    for it in items:
        by_status[it["status"]] = by_status.get(it["status"], 0) + 1
    stamp = datetime.now().strftime("%Y-%m-%dT%H:%M")

    lines = ["---", f"updated: {stamp}", f"total_open: {len(items)}", "by_status:"]
    for k in sorted(by_status):
        lines.append(f"  {k}: {by_status[k]}")
    lines.append("items:")
    for it in items:
        lines.append(f"  - id: {it['id']}")
        lines.append(f"    title: {yaml_escape(it['title'])}")
        lines.append(f"    status: {it['status']}")
        lines.append(f"    project: {yaml_escape(it['project'])}")
    lines += [
        "---",
        "# Open Tasks",
        "",
        "Generated by `scripts/parse_tasks.py` from `Tasks/TASKS.md` (open = unchecked",
        "box), project enriched from `Tasks/ledger.md`. Deterministic — no LLM.",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} — {len(items)} open tasks, by_status={by_status}")


if __name__ == "__main__":
    main()
